### ISSUE TITLE
提点意见

### ISSUE THREAD

**Issue by awklinux** [vicanso/cyber-tect#9]
1. 将检查结果导出到prometheus，并添加grafana模板
2. 增加检查节点，检查节点通过api到后端节点获取检查内容，然后检测，再将结果返回。

**Comment by vicanso** [comment]
1、后续可以考虑增加exporter
2、第二点是指http的检测吗？http检测支持自定义脚本来判断响应数据是否正常

**Comment by awklinux** [comment]
第二点可能是我没有表达清楚，我原来想的是觉得可以增加代理节点，因为之前公司http检测都是移动、联通、电信，还有像地域，像华东，华南，这样，阿里云http监控好像也是这样，添加代理节点，再汇总，另外以后我觉得软件开源，但是否可以运营一检测节点，供付费选择
另外，我觉得有个非常有必要的需求，就是https证书过期检查

**Comment by vicanso** [comment]
通过代理的方式去检测这个功能我后续版本增加一下。
https证书过期的检查已有，如果证书在7天内过期，则认为该服务检测不通过，出错信息为：证书将于%s过期

**Comment by vicanso** [comment]
最新版本http的检测已支持指定proxy的形式

**Comment by vicanso** [comment]
最新版本已增加支持上述功能

**Comment by Seevil** [comment]
能不能加入hook通知 比如钉钉 企业微信的通知

**Comment by vicanso** [comment]
@Seevil  [个人信息设置](https://github.com/vicanso/cyber-tect#%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF%E8%AE%BE%E7%BD%AE)支持设置http形式的告警推送，可以将告警信息推送至相应的告警服务。如果想测试体验一下，可以使用我部署的服务[cybertect](https://cybertect.npmtrend.com/#/)。

**Comment by Seevil** [comment]
> @Seevil 个人信息设置支持设置http形式的告警推送，[参考说明文档](https://github.com/vicanso/cyber-tect#%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF%E8%AE%BE%E7%BD%AE)，可以将告警信息推送至相应的告警服务。如果想测试体验一下，可以使用我部署的服务[cybertect](https://cybertect.npmtrend.com/#/)。

谢谢，看到了 强啊👍
